# Deployment da Aplicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics" 
      labels:
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: w3ll1n9t0n/fake-shop:latest
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: fakeshop-db-credentials
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: fakeshop-db-credentials
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fakeshop-db-credentials
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: fakeshop-db-credentials
                key: DB_NAME
          - name: FLASK_APP
            value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
