apiVersion: v1
kind: Secret
metadata:
  name: postgre-credentials
type: Opaque
data:
  POSTGRES_DB: ZmFrZXNob3A=       # Valor codificado em Base64 (fakeshop)
  POSTGRES_USER: ZmFrZXNob3A=     # Valor codificado em Base64 (fakeshop)
  POSTGRES_PASSWORD: UGcxMjM0     # Valor codificado em Base64 (Pg1234)
